name: "Publish to AKS Workflow"
description: "Publish to AKS Workflow"

inputs:
  version_to_deploy:
    description: "What version to deploy"
    required: false
    default: "latest"
  environment-to-deploy:
    description: "Which environment to deploy"
    required: false
    default: "stage"
  target:
    description: "Which environment to deploy"
    required: false
    default: "dev"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo Version ${{ inputs.version_to_deploy }}
      shell: bash
    - run: echo env ${{ inputs.environment-to-deploy }}
      shell: bash
    - run: echo env ${{ inputs.target }}
      shell: bash
