on: [push]

jobs:
  product-list:
    runs-on: ubuntu-latest
    name: Fetch all available products
    outputs:
      products: ${{steps.list-products.outputs.products}}
    steps:
      - name: List all products
        id: list-products
        uses: Hariprasath96/hello-world-javascript-action@v2.7

      - name: Get the output products-list
        run: echo "All products - ${{ steps.list-products.outputs.products }}"

  check:
    needs: [ product-list ]
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.product-list.outputs.products) }}
    steps:
      - uses: actions/checkout@v2 
      - run: |
          echo "${{ matrix.manifest }}"