on: [push]

jobs:
  product-list:
    runs-on: ubuntu-latest
    name: Fetch all available products
    outputs:
      products: ${{steps.list-products.outputs.products}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List all products
        id: list-products
        uses: ./

      - name: Get the output products-list
        run: echo "All products - ${{ steps.list-products.outputs.products }}"

  check:
    needs: [product-list]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.product-list.outputs.products) }}
    steps:
      - name: test
        id: test
        uses: actions/checkout@v2
      - run: |
          echo "${{ toJson(matrix.manifest) }}"
          echo "::set-output name=productName::${{ toJson(matrix.manifest.name) }}

      - name: trigger
        uses: ./products-1/${{steps.test.outputs.productName}}
        with:
          version_to_deploy: latest

  # TriggerProductWorkFlow:
  #   needs: [product-list]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       manifest: ${{ fromJson(needs.product-list.outputs.products) }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - uses: ./opschain-esg.yml
  #       with:
  #         version_to_deploy: latest
  #         environment-to-deploy: stage
