on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    outputs:
      data: ${{steps.hello.outputs.time}}
    steps:
      - name: Hello world action step
        id: hello
        uses: Hariprasath96/hello-world-javascript-action@v1.4
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The edited time was ${{ steps.hello.outputs.time }}"

  check:
    needs: [ hello_world_job ]
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.hello_world_job.outputs.data) }}
    steps:
      - uses: actions/checkout@v2 
      - run: |
          echo "${{ matrix.manifest }}"